spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MockProject_052024_Group2?useSSL=false
    username: root
    password: 13042003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
  open-in-view: false

server:
  port: 1903
