spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MockProject_052024_Group2?useSSl=false
    username: root
    password: 13042003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=MockProject_052024_Group2;encrypt=true;trustServerCertificate=true
#    username: sa
#    password: 123456789
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#        hibernate:
#          format_sql: true
#          dialect: org.hibernate.dialect.SQLServerDialect
#  main:
#    allow-bean-definition-overriding: true

server:
  port: 1903
